COPS-IITBHU/hackalog-frontend

components/HackathonCard/HackathonCard.js, css/style.css, pages/hackathons.js, pages/index.js, pages/submission/[id].js
The following pages were corrected with this PR -
1. `/`
2. `/hackathons`
3. `/submission/[id]`
Also the link in the Hackathon card was corrected to use the `slug` field.
=> Minor Fixes and Error Handling

pages/hackathon/[slug]/teams/[team_id]/submit.js, pages/submission/[id].js
1. Change button text to Submit from Login
2. Hide review section if not provided
3. Redirect to submission after submission
=> Submission Page Corrections

components/HackathonCard/HackathonCard.js, components/Profile/TeamCard.js, pages/hackathon/[slug]/index.js, pages/submission/[id].js
1. Profile Page TeamCard Link was added
2. Display of Review on Submission Page corrected
3. Many Case Handling Features on Hackathon Detail Page
4. Hackathon Cards Display Image was changed to the thumbnail
=> Case Handling on Hackathon Detail Page

pages/profile/[username].js
Footer was being called again in Profile Page
=> Remove Unwanted Footer Call

package-lock.json, package.json, pages/hackathon/[slug]/index.js
- Hackathon Detail Page - remove links to teams
- Corrected package.json repeated line
- Added and then commented submit button while submission endpoints are incomplete
- Corrected Title for the time being
=> Hackathon Detail Page remove links to teams

pages/hackathon/[slug]/index.js, pages/profile/[username].js
1. Corrected Undefined view when redirecting from Hackathons page
2. Corrected Unauthorised error on Teams API due to undefined slug
3. Removed redundant team link from Participants tab
4. Added Header Title to Profile Page
=> Bug Fixes on Hackathon Details Page

pages/hackathon/[slug]/index.js
I have corrected the spelling for **_started_**
=> Fixed a typo

pages/hackathon/[slug]/teams/[team_id]/submit.js
Alert for non-mutable submissions.
=> Submit Alert

pages/hackathon/[slug]/teams/[team_id]/submit.js
1. Fetch and display hackathon information on the submission page.
2. Reduced timeout to 500 
3. Case handling for Completed and Upcoming Hackathons
4. Case handling for teams who have already submitted
=> Updated Submit Page wrt Hackathon Details

components/Profile/EditProfileModal.js, context/auth.js, pages/hackathon/[slug]/index.js, pages/hackathon/[slug]/register.js, pages/hackathon/[slug]/teams/[team_id]/index.js, pages/hackathons.js, pages/submission/[id].js
Hi! Good day everyone! 
I'm solve issue #68
=> Remove Unnecessary Console Loggings

.github/pull_request_template.md, CONTRIBUTING.md, README.md, pages/hackathon/[slug]/index.js
This PR proposes the following changes:
1. Add Contributing Guidelines to the repository.
2. Update Readme with relevant repository information.
3. Introduce a Pull Request template.
4. Format the existing code (last unformatted commit).
=> Add Contributing Information and PR Template

components/Footer/Footer.js, pages/hackathon/[slug]/index.js, pages/profile/[username].js, pages/submission/[id].js
**Fixes**
Fixes #65 by @shubhanshu02 
As required in the issue I have added rel="noopener noreferrer" as an attribute to the anchor tags which have target="_blank"
**Checklist:**
=> Added rel = "noopener noreferrer" attribute in anchor tags with target="_blank"

package-lock.json, pages/profile/[username].js
**Fixes**
Fixes #89  by @shubhanshu02 
**Checklist:**
-   [ ] I have read the contribution guidelines in the repository.
-   [ ] My branch is up-to-date with upstream branch.
-   [ ] My pull request has a descriptive title (not a vague title like "Update package.json").
-   [ ] My code follows the established code style of the repository.
-   [ ] I have tried running the project locally and verified that there are no visible errors.
=>  Rename project tab to Teams

components/Header/Header.tsx
**Fixes**
Fixes part of #93 by @shubhanshu02 
**Checklist:**
=> Migrated from JavaScript to TypeScript : components/Header/Header.js

pages/hackathon/[slug]/index.tsx, types/backend.ts
**Fixes**
Fixes part of #93 
- Adds typescript support to `pages/hackathon/[slug]/index.js`
**Checklist:**
=> Fixes part of #93: Migrate pages/hackathon/[slug]/index.js to typescript

components/Profile/SkillOptions.ts
**Fixes**
Fixes part of #93 
**Checklist:**
=> migrated skilloptions.js to skilloptions.ts

pages/index.tsx
**Fixes**
Fixes part of #93 
**Checklist:**
=> migrated pages/index.js to (.tsx)

components/Buttons/signInButton.tsx, components/Header/Header.tsx, pages/hackathon/[slug]/index.tsx, pages/hackathons.tsx, pages/profile/[username].tsx, pages/submission/[id].tsx, styles/style.css
**Fixes**
Fixes #164 
**Checklist:**
=> added effects on hovering buttons

components/Footer/Footer.tsx
Updated social media handes link in footer to open in new tab.
**Checklist:**
=> Updated social media links to open in new tab

util/constants.ts
=> Fixed Backend Link

util/constants.ts
**Fixes**
Fixes #[issue number]
**Checklist:**
-   [ ] I have read the contribution guidelines in the repository.
-   [ ] My branch is up-to-date with upstream branch.
-   [ ] My pull request has a descriptive title (not a vague title like "Update package.json").
-   [ ] My code follows the established code style of the repository.
=> Added the backend URL
